### ISSUE TITLE
TaPD needs thorough update for AoI 3.1

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/TaPD#3]
Things down:
- The current code does not compile any more with the core-AoI.
- Preview is not working.
- May crash unexpectedly (but are there other kind of crashes? ;) )
- Does not work with the combined Textures and Material dialog.

Things up:
- The procedure itself.
- The main window and most of, what is in it.

There were a bunch of errors reported at compile. As I got those somehow patched up and the code compiled, I was able to create a test piece and reopen it for editing. Preview was not working though the missing interface method was added, so there is a more to go. There are a lot of type mismatches in the trinity of  `BFrame-EditingWindow-WindowWidget` which to some extent is quite possibly the reason behind the problems. This probably needs mapping out the good old paper an pencil way...

Also TaPD _(or it seemed so)_ crashed AoI at Save . The file was saved though and could be reopened and the TaPD object was intact too.
<hr>

I thought this would be worth calling it a project, but it turned out, that I can only create projects in my own fork, which probably is not that helpful, so I'll use the issue.

**Comment by Sailsman63** [comment]
I was looking at this earlier today. First thing that needs doing is to convert some of the more exotic characters to utf-8. Then look at the rest.

**Comment by Sailsman63** [comment]
Project created! Each issue should be a separate PR.

Feel free to propose more issues as they come up.
